Fix unused variable compiler warning
Error: repos/blehostd/apps/blehostd/src/bhd_gap.c:12:39: error: ‘bhd_gap_null_desc’ defined but not used [-Werror=unused-const-variable=]
 static const struct ble_gap_conn_desc bhd_gap_null_desc = {
                                       ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors